apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sample-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-sample
  template:
    metadata:
      labels:
        app: java-sample
    spec:
      containers:
      - name: java-sample
        image: yeshaswini984/docker-java-sample-webapp
        ports:
        - containerPort: 8080
